FROM openjdk
ENV LC_ALL C.UTF-8
RUN mkdir /javaconsumer
COPY target/rabbitmqExample-0.0.2-SNAPSHOT.jar /javaconsumer
WORKDIR /javaconsumer
ENV PATH=${PATH}:/javaconsumer
ENV rabbit.server rabbitMQServer
#CMD ["java", "-jar", "rabbitmqExample-0.0.2-SNAPSHOT.jar"]