version: "3"
services:

  javaConsumer:
    container_name: appRabbitConsumer
    build:
      context: .
      dockerfile: dockerfile_consumer
    depends_on:
      - rabbitmq
    command:
      bash -c "java -jar rabbitmqExample-0.0.1-SNAPSHOT.jar"
    restart: on-failure

  rabbitmq:
    container_name: rabbitMQServer
    image: rabbitmq:3.9.28
    ports:
      - 5672:5672