version: "3"
services:

  javaconsumer:
    container_name: appRabbitConsumer
    build:
      context: .
      dockerfile: dockerfile_consumer
    depends_on:
      - rabbitmq
 #   environment:
 #     - rabbit.server=rabbitMQServer
    ports:
      - "8080:8080"
    command:
      bash -c "java -jar /javaconsumer/rabbitmqExample-0.0.2-SNAPSHOT.jar"
    restart: on-failure

  rabbitmq:
    container_name: rabbitMQServer
    image: rabbitmq:3.11.9-management
    environment:
      - RABBITMQ_MANAGEMENT=ENABLE
    ports:
      - "5672:5672"
      - "15672:15672"